sudo: false
dist: trusty

language: node_js
node_js: '12'

# Since Travis is running on the Ubuntu 16+
# this library is necessary
# see https://github.com/cypress-io/cypress/issues/4069#issuecomment-488816887
addons:
  apt:
    packages:
      - libgconf-2-4

install:
  - yarn --frozen-lockfile --non-interactive

script:
  - yarn lint
  - yarn build
  - yarn test:ci
  - yarn test:ci:integration
  - yarn test:ci:integration:ssr
