version: 2

job_defaults: &job_defaults
  working_directory: ~/workspace/ngx-lottie
  docker:
    - image: circleci/node:14.15.0-browsers

cache_key: &cache_key yarn-ngx-lottie-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

yarn_install: &yarn_install
  run:
    name: Install dependencies
    command: yarn --frozen-lockfile --non-interactive

save_cache: &save_cache
  save_cache:
    name: Save Yarn cache and Cypress binary
    key: *cache_key
    paths:
      - ~/.cache
      - node_modules

restore_cache: &restore_cache
  restore_cache:
    name: Restore Yarn cache and Cypress binary
    keys:
      - *cache_key
      - yarn-ngx-lottie-v1-master
      - yarn-ngx-lottie-v1

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: ~/workspace
    paths:
      - ngx-lottie

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/workspace

jobs:
  build:
    <<: *job_defaults
    environment:
      HUSKY_SKIP_INSTALL: 'true'
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - run:
          name: Build ngx-lottie
          command: yarn build
      - *persist_to_workspace

  lint:
    <<: *job_defaults
    steps:
      - *attach_workspace
      - run:
          name: Run static linter
          command: yarn lint

  unit_tests:
    <<: *job_defaults
    steps:
      - *attach_workspace
      - run:
          name: Run unit tests
          command: yarn test:ci

  integration_tests_ssr:
    <<: *job_defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Run SSR tests
          command: yarn test:ci:integration:ssr

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - lint:
          requires:
            - build

      - unit_tests:
          requires:
            - build

      - integration_tests_ssr:
          requires:
            - build
